version: '3'

services:
    api:
        restart: always
        build: ./api
        volumes: ['./api:/app']
        ports:
            - 8081:80
    
    app:
        restart: always
        build: ./app
        volumes: ['./app/src:/app/src']
        depends_on:
            - api
        ports:
            - 8080:8080
        environment: 
            - CHOKIDAR_USEPOLLING=true